// Copyright (c) 2008-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// @File								tcds_kernel_process.script
//

//! @SYMTestSuiteName               	DT-kernelcrash-process
//! @SYMScriptTestEnvironment       	TEF

LOAD_SUITE tcds_kernel



START_TESTCASE                DT-kernelcrash-process-0001
//! @SYMTestCaseID              DT-kernelcrash-process-0001
//! @SYMTestCaseDesc            Check for valid system crash ELF
//! @SYMTestPriority            High
//! @SYMTestActions             Loads SELF, process crash and makes sure the file is valid
//! @SYMTestExpectedResults     Valid ELF
//! @SYMTestType                CT
//! @SYMCreationDate            26/11/2008
//! @SYMAuthor                  stephenroberts
//! @SYMTestStatus              2. Functional
    START_TEST_BLOCK    100    tcds_kernel \data\tcds_kernel.ini
       	CREATE_OBJECT	CProcessCrashWrapper	processb 
            COMMAND		    processb	      NewL
			COMMAND         processb          ReadCrashInfo
			COMMAND         processb          LoadPlugins
			COMMAND         processb          ConfigurePlugins   SELFFile_Path
			COMMAND         processb          ProcessCrash
			COMMAND         processb          UnLoadPlugins
			COMMAND         processb          ProcessELFFile

    END_TEST_BLOCK
END_TESTCASE DT-kernelcrash-process-0001


START_TESTCASE                DT-kernelcrash-process-0002
//! @SYMTestCaseID              DT-kernelcrash-process-0002
//! @SYMTestCaseDesc            Deletes all crashes
//! @SYMTestPriority            High
//! @SYMTestActions             Delete all crashes in the partition
//! @SYMTestExpectedResults     Partition should be deleted
//! @SYMTestType                CT
//! @SYMCreationDate            26/11/2008
//! @SYMAuthor                  stephenroberts
//! @SYMTestStatus              2. Functional
    START_TEST_BLOCK    100    tcds_kernel \data\tcds_kernel.ini
       	CREATE_OBJECT	CProcessCrashWrapper	processb 
       	    COMMAND		    processb	      NewL  
			COMMAND         processb          ReadCrashInfo
			COMMAND         processb          DeleteAllCrashes
    END_TEST_BLOCK
END_TESTCASE DT-kernelcrash-process-0002


START_TESTCASE                DT-kernelcrash-process-0003
//! @SYMTestCaseID              DT-kernelcrash-process-0003
//! @SYMTestCaseDesc            Configure the SCM to dump minimal data
//! @SYMTestPriority            Medium
//! @SYMTestActions             Configure the SCM to dump minimal data
//! @SYMTestExpectedResults     Configuration should suceed
//! @SYMTestType                CT
//! @SYMCreationDate            26/11/2008
//! @SYMAuthor                  stephenroberts
//! @SYMTestStatus              2. Functional
    START_TEST_BLOCK    100    tcds_kernel \data\tcds_kernel.ini
       	CREATE_OBJECT	CProcessCrashWrapper	processb 
       	    COMMAND		    processb	      NewL  
			COMMAND         processb          ConfigureSCMZeroPriority
    END_TEST_BLOCK
END_TESTCASE DT-kernelcrash-process-0003


START_TESTCASE                DT-kernelcrash-process-0004
//! @SYMTestCaseID              DT-kernelcrash-process-0004
//! @SYMTestCaseDesc            Checks for multiple crashes
//! @SYMTestPriority            High
//! @SYMTestActions             Crash board 4 times. Make sure we see 4 crashes
//! @SYMTestExpectedResults     4 crashes found
//! @SYMTestType                CT
//! @SYMCreationDate            26/11/2008
//! @SYMAuthor                  stephenroberts
//! @SYMTestStatus              2. Functional
    START_TEST_BLOCK    100    tcds_kernel \data\tcds_kernel.ini
       	CREATE_OBJECT	CProcessCrashWrapper	processb 
       	    COMMAND		    processb	      NewL  
			COMMAND         processb          ReadCrashInfoAndCheckForFour
	END_TEST_BLOCK
END_TESTCASE DT-kernelcrash-process-0004


