// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
// @File								te_cdsconnections.script
//

//! @SYMTestSuiteName               	DT-coredumpserver-connections
//! @SYMScriptTestEnvironment       	TEF

PRINT Running te_coredumpserver.CDSCONNECTIONS

LOAD_SERVER te_coredumpserverSuite

START_TESTCASE                DT-coredumpserver-connections-0001
//! @SYMTestCaseID              DT-coredumpserver-connections-0001
//! @SYMTestCaseDesc            Test that we can connect to the CDS
//! @SYMTestPriority            Critical
//! @SYMTestActions             Test that we can connect to the CDS
//! @SYMTestExpectedResults     Pass
//! @SYMTestType                CT
//! @SYMCreationDate            26/11/2008
//! @SYMAuthor                  stephenroberts
//! @SYMTestStatus              2. Functional
RUN_TEST_STEP 100 te_coredumpserverSuite CDSConnectionsStep
END_TESTCASE DT-coredumpserver-connections-0001
PRINT Completed te_coredumpserver.CDSCONNECTIONS


