// Copyright (c) 2007-2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description:
//

//! @File								te_testformatter.script
//! @SYMTestSuiteName               	Core Dump Application Crash
//! @SYMScriptTestEnvironment       	TEF

PRINT Running te_coredumpserver.TestFormatterUserSide

LOAD_SERVER te_coredumpserverSuite

RUN_TEST_STEP 100 te_coredumpserverSuite TestFormatterUserSideStep

PRINT Completed te_coredumpserver.TestFormatterUserSide
