//
// Copyright (c) 2009 Nokia Corporation and/or its subsidiary(-ies).
// All rights reserved.
// This component and the accompanying materials are made available
// under the terms of "Eclipse Public License v1.0"
// which accompanies this distribution, and is available
// at the URL "http://www.eclipse.org/legal/epl-v10.html".
//
// Initial Contributors:
// Nokia Corporation - initial contribution.
//
// Contributors:
//
// Description: 
//
//
PRINT Run all Sample Tests 
//
LOAD_SUITE filewritertestserver -SharedData
//

#
RUN_TEST_STEP 100 filewritertestserver FileWriterTestStep1
RUN_TEST_STEP 100 filewritertestserver FileWriterTestStep2

// Open (create) 11 files in c:\dumpfiles
PREFIX RUN_UTILS
MkDir c:\dumpfiles
REMOVE_PREFIX

RUN_TEST_STEP 100 filewritertestserver FileWriterTestStep3
RUN_TEST_STEP 100 filewritertestserver FileWriterTestStep4
RUN_TEST_STEP 100 filewritertestserver FileWriterTestStep5
